; Configuration command-line interface script directory.
[command-line-interface]
; Command shell in which directory.
CLI_SHELL_DIRECTORY=${CLI_DIRECTORY}/kind
; Command utils in which directory.
CLI_UTILS_DIRECTORY=${CLI_DIRECTORY}/utils

; Configuration workflow setting.
[workflow]
